[상품 디테일 페이지 구현]Add:projects detail view
wecode-bootcamp-korea/34-2nd-greeneeds-backend pull request #11
Opened 2022-07-10 05:01 UTC by KJY0627

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
상품 디테일 페이지 구현

![Screen Shot 2022-07-10 at 1 58 46 PM](https://user-images.githubusercontent.com/100059297/178131969-8f09c798-2341-46cd-b6b0-8e1761e96b63.png)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상품 디테일 페이지 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- annotate 사용법을 숙지하는 기회였습니다

<br />

## :: 기타 질문 및 특이 사항

2022-07-11 01:50 UTC, Kang-kyunghun requested changes
수정 사항 반영 후 테스트 코드 작성해 주세요.

2022-07-11 01:50 UTC, Kang-kyunghun commented on greeneeds/projects/views.py
> +
공백 제거해 주세요.

2022-07-11 01:50 UTC, Kang-kyunghun commented on greeneeds/projects/views.py
> +             images   = ProjectImage.objects.filter(project_id=project_id)
이미 project 정보를 가져왔으므로 아래와 같이 작성할 수 있습니다.
```suggestion
             images   = project.projectimage_set.all()
```

2022-07-11 01:50 UTC, Kang-kyunghun commented on greeneeds/projects/views.py
> +             } for image in images]
```suggestion
             images = [{
                 "id"  : image.id,
                 "url" : image.image_url
             } for image in images]
```

2022-07-11 02:17 UTC, KJY0627 commented on greeneeds/projects/views.py
> +
네 테스트 코드 추가해서 다시 푸시하겠습니다!

2022-07-12 06:45 UTC, KJY0627 commented
상품 디테일 뷰랑 테스트 아까 리뷰 해주신대로 수정해서 다시 푸시했습니다! 감사합니다

2022-07-12 09:08 UTC, merged