[Users] UserInfoView 구현
wecode-bootcamp-korea/34-2nd-greeneeds-backend pull request #12
Opened 2022-07-11 03:29 UTC by HyeonWooJo

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 로그인 후 nav 창에 필요한 유저 정보 전달 API 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. GET method를 사용해서 user_id, email, nickname 전달

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 없음

<br />

## :: 기타 질문 및 특이 사항
- 없음

2022-07-11 07:55 UTC, Kang-kyunghun requested changes

2022-07-11 07:55 UTC, Kang-kyunghun commented on greeneeds/greeneeds/settings.py
> +from my_settings import SECRET_KEY, DATABASES, KAKAO_REST_API_KEY, KAKAO_REDIRECT_URI, ALGORITHM, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
```suggestion
from my_settings import (
    SECRET_KEY, 
    DATABASES, 
    KAKAO_REST_API_KEY, 
    KAKAO_REDIRECT_URI, 
    ALGORITHM, 
    AWS_ACCESS_KEY_ID, 
    AWS_SECRET_ACCESS_KEY
)
```

2022-07-11 07:55 UTC, Kang-kyunghun commented on greeneeds/users/urls.py
> +    path('/info' , UserInfoView.as_view()),
```suggestion
    path('' , UserInfoView.as_view()),      
```

2022-07-11 07:55 UTC, Kang-kyunghun commented on greeneeds/users/views.py
> +class UserInfoView(View):
```suggestion
class UserView(View):
```

2022-07-11 07:55 UTC, Kang-kyunghun commented on greeneeds/users/views.py
> +        return JsonResponse({'RESULT': result}, status=200)
key 값은 주로 스네이크케이스로 사용하는 경우가 많습니다.
```suggestion
        return JsonResponse({'result': result}, status=200)
```

2022-07-11 07:55 UTC, Kang-kyunghun commented on greeneeds/core/utils.py
> +
카카오 관련 코드는 따로 올려주세요.

2022-07-12 04:37 UTC, HyeonWooJo commented
리뷰 주신 사항 모두 수정하였습니다.
동시에 UserView에 대해서 tests.py 만들어서 push 하였습니다!

2022-07-13 05:09 UTC, closed without merging