[Projects] ProjectUploadView 구현
wecode-bootcamp-korea/34-2nd-greeneeds-backend pull request #14
Opened 2022-07-11 06:49 UTC by HyeonWooJo

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 이미지와 텍스트를 받아 DB에 저장하는 API 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. formdata 받기
- formdata 형식으로 이미지와 텍스트를 받음 
- S3ImageUploaderView에서 이미지를 먼저 받아서 이미지 url을 return

2. ProductUploaderView
- 로그인 한 사람만 사용할 수 있도록 login_decorator 사용
- Project class에 필요한 formdata 형식으로 받은 텍스트 데이터를 통해서 Project 객체 생성
- project=Project.objects.create()를 사용하여 project 객체와 이미지 url을 받아서 ProjectImage객체 생성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 이미지와 텍스트를 동시에 POST를 통해서 받을 경우 formdata로 통일해서 받는다는 것을 알게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항
- 없음

2022-07-13 09:22 UTC, HyeonWooJo commented
conflict 해결하고 push 하였습니다!

2022-07-14 03:00 UTC, Kang-kyunghun requested changes

2022-07-14 03:00 UTC, Kang-kyunghun commented on greeneeds/projects/views.py
> +class ProjectUploadView(View):
해당 api는 정확히 따져보면 project 정보를 db에 저장하는 view 입니다. 그 과정에서 일부 데이터를 s3에 저장하는 과정이 있는거죠

즉, Project 리스트에 하나의 Project를 추가는 과정이라고 볼 수 있습니다.
그래서 ProjectListView에 post method로 구현하는 것이 더 자연스러울 것 같습니다.

2022-07-14 03:00 UTC, Kang-kyunghun commented on greeneeds/projects/views.py
> +               upload_img_url = FileUpload(s3_client).upload(file)
객체를 생성하지 않고 바로 해당 method까지 바로 진행할 경우 실용성이 많이 떨어집니다.
다시 객체가 필요할 경우 객체를 다시 할당 해야 되고, 다시 할당된 객체는 처음에 사용했던 객체의 정보를 가지고 있지 않습니다.

```suggestion
               s3_client      = FileUpload(s3_client)
               upload_img_url = s3_client.upload(file)
```

2022-07-14 03:00 UTC, Kang-kyunghun commented on greeneeds/projects/views.py
> +                    category        = Category.objects.get(id=request.POST['category']),
존재하지 않는 카테고리에 대해 예외처리 추가해 주세요.

2022-07-14 03:00 UTC, Kang-kyunghun commented on greeneeds/projects/views.py
> +               return JsonResponse({'MESSAGE' : 'KEY_ERROR'}, status = 400)
key 값은 소문자로 바꿔 주세요.

2022-07-14 03:54 UTC, HyeonWooJo commented
수정하여 다시 push 하였습니다.

2022-07-14 04:21 UTC, HyeonWooJo commented
[Project 올리기 API POSTMAN 캡쳐]

<img width="1104" alt="스크린샷 2022-07-14 오후 1 19 37" src="https://user-images.githubusercontent.com/65996045/178897884-6d592fe8-2136-4587-9724-1e4216d9ba55.png">

2022-07-14 05:36 UTC, Kang-kyunghun commented
반드시 Transaction에 대해 나중에 적용하셔야 합니다~!

2022-07-14 05:36 UTC, merged

2022-07-14 06:37 UTC, HyeonWooJo commented
넵 적용하여 push 하였습니다!