[상품(프로젝트)리스트, 디테일 뷰]Add:product list view
wecode-bootcamp-korea/34-2nd-greeneeds-backend pull request #4
Opened 2022-07-07 01:38 UTC by KJY0627

Fix:product detail view

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

- 상품(프로젝트)메인 페이지를 두가지 종류로 sort 할 수 있도록 [1. 좋아요 갯수 순서 2. 마감기한 순서] view 작성
- +디테일 view 작성

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 필요없는 코드없이 작성을 할 수 있도록 노력을 했습니다

<br />

## :: 기타 질문 및 특이 사항
- datetime 을 잘 사용했는지, 장고 클래스 데이터를 잘 불러왔는 지

2022-07-07 02:09 UTC, bigfanoftim requested changes

2022-07-07 02:09 UTC, bigfanoftim commented on greeneeds/greeneeds/settings.py
> +
불필요한 주석을 지워주세요.
```suggestion
```

2022-07-08 01:20 UTC, Kang-kyunghun requested changes

2022-07-08 01:20 UTC, Kang-kyunghun commented on greeneeds/projects/views.py
> +             return JsonResponse({'message' : 'PROJECT_DOES_NOT_EXIST'}, status = 400)
디테일이 그대로 올라왔습니다.
디테일은 PR을 분리해서 올려주세요.

2022-07-08 01:20 UTC, Kang-kyunghun commented on greeneeds/projects/views.py
> +                projects = Project.objects.order_by('?')
코드 내용을 보면 프론트 query parameter 를 받아서 분기처릴 하는 것으로 보입니다.
지금은 하나의 key 'order'에 의해 분기가 처리 되므로 이와 같은 상황에서는 dictionary를 사용하여 조금 더 가독성 있는 코드를 작성할 수 있습니다. 
```suggestion
            order_set = {
                'like'   : '-like_count',
                'recent' : 'end_datetime',
                'random  : '?'
            }
            
            order_field = order_set.get(order_condition, '?')
          
            projects = Project.objects.annotate(like_count=Count('Like')).order_by(order_field) 
```

2022-07-08 01:20 UTC, Kang-kyunghun commented on greeneeds/projects/views.py
> +                 'remain_days'   : datetime.date(project.end_datetime)-datetime.now()
날짜 계산 부분은 다시 한 번 생각해 보세요.

2022-07-08 01:20 UTC, Kang-kyunghun commented on greeneeds/greeneeds/settings.py
> +
해당 코드 주석을 한 이유가 있을까요?

프로젝트 진행에 있어 두 분 모두 M1이 아니시라면 삭제해도 될 것 같습니다.

2022-07-13 06:54 UTC, closed without merging